apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-limiter-controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: rate-limiter-controller-manager
      containers:
      - command:
        - /manager
        args:
        - --metrics-addr=:8080
        image: kaswfy/rate-limiter-operator:latest  # Replace with your registry
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: 8080
          name: metrics
      terminationGracePeriodSeconds: 10