//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderRateLimit) DeepCopyInto(out *HeaderRateLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderRateLimit.
func (in *HeaderRateLimit) DeepCopy() *HeaderRateLimit {
	if in == nil {
		return nil
	}
	out := new(HeaderRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitConfig) DeepCopyInto(out *RateLimitConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitConfig.
func (in *RateLimitConfig) DeepCopy() *RateLimitConfig {
	if in == nil {
		return nil
	}
	out := new(RateLimitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RateLimitConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitConfigList) DeepCopyInto(out *RateLimitConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RateLimitConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitConfigList.
func (in *RateLimitConfigList) DeepCopy() *RateLimitConfigList {
	if in == nil {
		return nil
	}
	out := new(RateLimitConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RateLimitConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitConfigSpec) DeepCopyInto(out *RateLimitConfigSpec) {
	*out = *in
	if in.MaxRequestsByIpRps != nil {
		in, out := &in.MaxRequestsByIpRps, &out.MaxRequestsByIpRps
		*out = new(int32)
		**out = **in
	}
	if in.MaxRequestsByUserRps != nil {
		in, out := &in.MaxRequestsByUserRps, &out.MaxRequestsByUserRps
		*out = new(int32)
		**out = **in
	}
	if in.MaxRequestsByLikeRouteRps != nil {
		in, out := &in.MaxRequestsByLikeRouteRps, &out.MaxRequestsByLikeRouteRps
		*out = new(int32)
		**out = **in
	}
	if in.EnvoyPort != nil {
		in, out := &in.EnvoyPort, &out.EnvoyPort
		*out = new(int32)
		**out = **in
	}
	if in.HeaderRateLimits != nil {
		in, out := &in.HeaderRateLimits, &out.HeaderRateLimits
		*out = make([]HeaderRateLimit, len(*in))
		copy(*out, *in)
	}
	if in.IngressPort != nil {
		in, out := &in.IngressPort, &out.IngressPort
		*out = new(int32)
		**out = **in
	}
	if in.EgressPort != nil {
		in, out := &in.EgressPort, &out.EgressPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitConfigSpec.
func (in *RateLimitConfigSpec) DeepCopy() *RateLimitConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RateLimitConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitConfigStatus) DeepCopyInto(out *RateLimitConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitConfigStatus.
func (in *RateLimitConfigStatus) DeepCopy() *RateLimitConfigStatus {
	if in == nil {
		return nil
	}
	out := new(RateLimitConfigStatus)
	in.DeepCopyInto(out)
	return out
}
