apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rate-limiter-manager-role
rules:
- apiGroups: ["kaswfy.io"]
  resources: ["ratelimitconfigs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["kaswfy.io"]
  resources: ["ratelimitconfigs/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]