apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rate-limiter-manager-rolebinding
  labels:
    app.kubernetes.io/name: rate-limiter-operator
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rate-limiter-manager-role
subjects:
- kind: ServiceAccount
  name: rate-limiter-controller-manager
  namespace: system