replicaCount: 1

image:
  repository: kaswfy/rate-limiter-operator  # Replace with your registry/repo
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: "rate-limiter-controller-manager"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

metrics:
  enabled: true
  port: 8080